template: |
  ## Changes

  $CHANGES

autolabeler:
  - label: "chore"
    files:
      - "*.md"
    branch:
      - '/docs{0,1}\/.+/'
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "enhancement"
    branch:
      - '/feat\/.+/'
    body:
      - "/JIRA-[0-9]{1,4}/"

references:
  - main
  - release
  - v.+
